apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-10-04T20:53:11Z"
  generation: 1
  labels:
    app: prometheus
  name: prometheus
  namespace: default
  resourceVersion: "3379"
  selfLink: /apis/apps/v1/namespaces/default/deployments/prometheus
  uid: 4873c39c-c003-4f43-9972-4149da10dd5d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prometheus
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus-sa
      containers:
      - image: prom/prometheus
        imagePullPolicy: Always
        name: prometheus
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - name: prometheus
            mountPath: /etc/prometheus/
      - image: prom/alertmanager
        imagePullPolicy: IfNotPresent
        name: alertmanager
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - name: alertmanager
            mountPath: /etc/alertmanager/
      volumes: 
        - name: prometheus
          configMap: 
            defaultMode: 420
            name: prometheus
        - name: alertmanager
          configMap: 
            defaultMode: 420
            name: alertmanager
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-10-04T20:53:31Z"
    lastUpdateTime: "2020-10-04T20:53:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-10-04T20:53:11Z"
    lastUpdateTime: "2020-10-04T20:53:31Z"
    message: ReplicaSet "prometheus-5f8b675f8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
