apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-10-04T20:54:00Z"
  labels:
    app: prometheus
  name: prometheus
  namespace: default
  resourceVersion: "3418"
  selfLink: /api/v1/namespaces/default/services/prometheus
  uid: d2181179-e1c2-40e3-99ef-1471cf57345e
spec:
  clusterIP: 10.107.59.144
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30278
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
