apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-10-04T20:42:28Z"
  generation: 1
  labels:
    app: hello
  name: hello
  namespace: default
  resourceVersion: "2668"
  selfLink: /apis/apps/v1/namespaces/default/deployments/hello
  uid: 9b4da2a9-864c-484c-b1df-74d9b884c40b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hello
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello
    spec:
      containers:
      - image: sparlor/scottyfullstack:hello
        imagePullPolicy: IfNotPresent
        name: scottyfullstack
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-10-04T20:44:01Z"
    lastUpdateTime: "2020-10-04T20:44:01Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-10-04T20:42:28Z"
    lastUpdateTime: "2020-10-04T20:44:01Z"
    message: ReplicaSet "hello-d445b4cc9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
